### ISSUE TITLE
Upgrading graphql Gem to 1.12.4 Causes Connection Error

### ISSUE THREAD

**Issue by Petercopter** [palkan/action_policy-graphql#42]
### Tell us about your environment

**Ruby Version:** 
3.0

**Framework Version (Rails, whatever):** 
Rails 6.1

**Action Policy Version:**
0.5.5

**Action Policy GraphQL Version:**
0.5.2

### What did you do?
Upgraded graphql gem from `1.12.3` to `1.12.4`

### What did you expect to happen?
Connections would continue working

### What actually happened?

With this code
```
    field :rewards,
          RewardType.connection_type,
          'Returns a paginated list of all rewards',
          authorized_scope: true,
          null: false
```
I get
```
ActionPolicy::NotFound:
       Couldn't find policy class for [#<Types::QueryType:0x00005577c3abc2b0 @object=nil, @context=#<Query::Context ...>, @__authorization_context={:user=>#<User ancestry: nil, id: 795, email: [FILTERED], created_at: "2021-02-16 17:43:54.930691000 +0000", updated_at: "2021-02-16 17:43:55.234755800 +0000", account_id: 989, first_name: [FILTERED], last_name: [FILTERED], employee_number: [FILTERED], manager_id: nil, hire_date: nil, relocate: nil, short_term_plan: nil, long_term_plan: nil, last_email_sent: nil, status: "active", jti: "c4a742a6-7978-467a-85b3-a2cd0691c111", potential_rating_id: nil, departure_risk_id: nil, succession_time_frame_id: nil, experience_before_next_role: "Retro photo booth hammock waistcoat marfa sriracha...", performance_rating_id: nil, review_frequency: "monthly", enabled: true, role_group_id: nil, uuid: "a7769f4e-8694-44c3-a7bf-38e49cc6180a">}, @__policies_cache__={"//users/795-20210216174355234755/347440"=>nil}, @authorization_namespace=Types>, "Couldn't find implicit authorization target for Types::QueryType. Please, provide policy class explicitly using `with` option or define the `implicit_authorization_target` method."] (Array)
     # /bundle/ruby/3.0.0/gems/action_policy-0.5.5/lib/.rbnext/1995.next/action_policy/behaviours/policy_for.rb:42:in `implicit_authorization_target!'
     # /bundle/ruby/3.0.0/gems/action_policy-0.5.5/lib/.rbnext/1995.next/action_policy/behaviours/scoping.rb:17:in `authorized_scope'
     # /bundle/ruby/3.0.0/gems/action_policy-graphql-0.5.2/lib/action_policy/graphql/authorized_field.rb:120:in `after_resolve'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:769:in `block (2 levels) in with_extensions'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:766:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:766:in `block in with_extensions'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:115:in `after_lazy'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:764:in `with_extensions'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:696:in `public_send_field'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:609:in `block in resolve'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:115:in `after_lazy'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:607:in `resolve'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:272:in `block (4 levels) in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/tracing.rb:66:in `trace'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:271:in `block (3 levels) in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/query.rb:364:in `block in with_error_handling'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/errors.rb:45:in `with_error_handling'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/query.rb:363:in `with_error_handling'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:270:in `block (2 levels) in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:432:in `resolve_with_directives'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:267:in `block in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:516:in `after_lazy'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:214:in `evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:206:in `block in evaluate_selection'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:132:in `block (2 levels) in coerce_arguments'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:111:in `block in coerce_arguments'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:110:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:110:in `coerce_arguments'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/arguments_cache.rb:49:in `dataload_for'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:205:in `evaluate_selection'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:142:in `block (2 levels) in evaluate_selections'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:141:in `block in evaluate_selections'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:140:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:140:in `evaluate_selections'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:62:in `block in run_eager'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:61:in `run_eager'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter.rb:77:in `block in evaluate'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/tracing.rb:66:in `trace'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter.rb:76:in `evaluate'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter.rb:49:in `begin_query'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:85:in `begin_query'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:103:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:103:in `each_with_index'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/tracing.rb:66:in `trace'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:60:in `run_queries'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:50:in `run_all'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:1690:in `multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:1661:in `execute'
     # ./app/controllers/graphql_controller.rb:13:in `execute'
     # /bundle/ruby/3.0.0/gems/actiontext-6.1.2.1/lib/action_text/rendering.rb:20:in `with_renderer'
     # /bundle/ruby/3.0.0/gems/actiontext-6.1.2.1/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
     # /bundle/ruby/3.0.0/gems/rack-attack-6.5.0/lib/rack/attack.rb:99:in `call'
     # /bundle/ruby/3.0.0/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
     # /bundle/ruby/3.0.0/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
     # /bundle/ruby/3.0.0/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth/middleware.rb:23:in `call'
     # /bundle/ruby/3.0.0/gems/rack-attack-6.5.0/lib/rack/attack.rb:113:in `call'
     # /bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
     # /bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
     # /bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
     # /bundle/ruby/3.0.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
     # /bundle/ruby/3.0.0/gems/railties-6.1.2.1/lib/rails/rack/logger.rb:26:in `block in call'
     # /bundle/ruby/3.0.0/gems/railties-6.1.2.1/lib/rails/rack/logger.rb:26:in `call'
     # /bundle/ruby/3.0.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /bundle/ruby/3.0.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
     # /bundle/ruby/3.0.0/gems/railties-6.1.2.1/lib/rails/engine.rb:539:in `call'
     # /bundle/ruby/3.0.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /bundle/ruby/3.0.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /bundle/ruby/3.0.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/requests/graphql/queries/rewards_spec.rb:120:in `block (4 levels) in <top (required)>'
     # /bundle/ruby/3.0.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

With
```
field :rewards,
          RewardType.connection_type,
          'Returns a paginated list of all rewards',
          authorized_scope: { with: RewardPolicy },
          null: false
```

I get 
```
ActionPolicy::UnrecognizedScopeTarget:
       Couldn't infer scope type for GraphQL::Pagination::ActiveRecordRelationConnection instance
     # /bundle/ruby/3.0.0/gems/action_policy-0.5.5/lib/action_policy/policy/scoping.rb:105:in `resolve_scope_type'
     # /bundle/ruby/3.0.0/gems/action_policy-0.5.5/lib/.rbnext/1995.next/action_policy/behaviours/scoping.rb:31:in `authorization_scope_type_for'
     # /bundle/ruby/3.0.0/gems/action_policy-0.5.5/lib/.rbnext/1995.next/action_policy/behaviours/scoping.rb:19:in `authorized_scope'
     # /bundle/ruby/3.0.0/gems/action_policy-graphql-0.5.2/lib/action_policy/graphql/authorized_field.rb:120:in `after_resolve'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:769:in `block (2 levels) in with_extensions'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:766:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:766:in `block in with_extensions'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:115:in `after_lazy'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:764:in `with_extensions'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:696:in `public_send_field'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:609:in `block in resolve'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:115:in `after_lazy'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/field.rb:607:in `resolve'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:272:in `block (4 levels) in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/tracing.rb:66:in `trace'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:271:in `block (3 levels) in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/query.rb:364:in `block in with_error_handling'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/errors.rb:45:in `with_error_handling'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/query.rb:363:in `with_error_handling'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:270:in `block (2 levels) in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:432:in `resolve_with_directives'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:267:in `block in evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:516:in `after_lazy'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:214:in `evaluate_selection_with_args'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:206:in `block in evaluate_selection'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:132:in `block (2 levels) in coerce_arguments'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:111:in `block in coerce_arguments'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:110:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema/member/has_arguments.rb:110:in `coerce_arguments'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/arguments_cache.rb:49:in `dataload_for'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:205:in `evaluate_selection'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:142:in `block (2 levels) in evaluate_selections'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:141:in `block in evaluate_selections'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:140:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:140:in `evaluate_selections'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:62:in `block in run_eager'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter/runtime.rb:61:in `run_eager'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter.rb:77:in `block in evaluate'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/tracing.rb:66:in `trace'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter.rb:76:in `evaluate'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/interpreter.rb:49:in `begin_query'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:85:in `begin_query'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:103:in `each'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:103:in `each_with_index'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/tracing.rb:66:in `trace'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:60:in `run_queries'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/execution/multiplex.rb:50:in `run_all'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:1690:in `multiplex'
     # /bundle/ruby/3.0.0/gems/graphql-1.12.4/lib/graphql/schema.rb:1661:in `execute'
     # ./app/controllers/graphql_controller.rb:13:in `execute'
     # /bundle/ruby/3.0.0/gems/actiontext-6.1.2.1/lib/action_text/rendering.rb:20:in `with_renderer'
     # /bundle/ruby/3.0.0/gems/actiontext-6.1.2.1/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
     # /bundle/ruby/3.0.0/gems/rack-attack-6.5.0/lib/rack/attack.rb:99:in `call'
     # /bundle/ruby/3.0.0/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
     # /bundle/ruby/3.0.0/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
     # /bundle/ruby/3.0.0/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth/middleware.rb:23:in `call'
     # /bundle/ruby/3.0.0/gems/rack-attack-6.5.0/lib/rack/attack.rb:113:in `call'
     # /bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
     # /bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
     # /bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
     # /bundle/ruby/3.0.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
     # /bundle/ruby/3.0.0/gems/railties-6.1.2.1/lib/rails/rack/logger.rb:26:in `block in call'
     # /bundle/ruby/3.0.0/gems/railties-6.1.2.1/lib/rails/rack/logger.rb:26:in `call'
     # /bundle/ruby/3.0.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /bundle/ruby/3.0.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
     # /bundle/ruby/3.0.0/gems/railties-6.1.2.1/lib/rails/engine.rb:539:in `call'
     # /bundle/ruby/3.0.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /bundle/ruby/3.0.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /bundle/ruby/3.0.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/requests/graphql/queries/rewards_spec.rb:146:in `block (4 levels) in <top (required)>'
     # /bundle/ruby/3.0.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

**Comment by palkan** [comment]
Looks like this change broke our integration: https://github.com/rmosolgo/graphql-ruby/pull/3326/files
